config/routes.rb
DPChess::Application.routes.draw do
  devise_for :users

  root 'static_pages#index'
  resource :dashboard, :only => [:show]
  resources :games
  resources :pieces

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
 before_action :authenticate_user!, :only => [:show]
	def show
		@games = Game.all
		@opengames = Game.where("games.black_player_id IS NULL")
	end


end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/show.html.erb
<h1 class="text-center">Welcome to your Deep Purple dashboard!</h1>
<br />

<div class="dash">
</div>

<!-- If game creators make game public, then other users
can access it to view from here -->
<div class="col-xs-4 col-xs-offset-1">	
	<h2>All Public games</h2>
	<% @games.each do |game| %>
		<table>
			<tr><%= link_to game.name, game_path(game) %></tr>
		</table>
	<% end %>
</div>

<div class="col-xs-4 col-xs-offset-1">	
	<h2>Games with seats available</h2>
	<i>Click to Join</i><br />
	<% if @opengames.nil? %>
		<b>No open games. Click below to Create New Game</b>
		<%= link_to 'Create New Game', games_path, :method => :post, :class => 'btn btn-primary' %>
	<% else %>
		<% @opengames.each do |game| %>
		<table>
			<tr><%= link_to game.name, '#' %></tr>
		</table>	
		<% end %>
	<% end %>

</div>

<br class="clr" />

<div class="col-xs-4 col-xs-offset-1">	
	<h2>Your games in session</h2>
	<%# current_user.games.each do |game| %>
		<h3 class="text-center">
			<%#= link_to game.name, '#' %>
		</h3>
		<br />
	<%# end %>
	<%= link_to 'Create New Game', new_game_path, :class => 'btn btn-primary' %>
</div>


<br class="clr" />